# Define the categories and keywords
categories = {
    "M&A": ["merge", "acquire", " bid", "takeover", " buy", "buys", "acquisition", "divest", "consolidation", "merger", "purchase"],
    "Partnerships": ["partner", "partnership", "join", "collaboration", "alliance", "cooperation"],
    "Spinoff": [" sell ", "sell-off", " spin", "spin-off", "spinoff", "separation", "divestiture"],
    "Economic environment": [" crisis ", " interest ", " rates", "economic downturn", "recession", "inflation", "monetary policy", "macroeconomic"],
    "Regulatory": ["regulator", "rule", "regulation", "FCA", "PSR", "Bank of England", "government", "license", "authorisation", "compliance", "enforcement"],
    "Entry": ["enter", " roll", " rolls", "new product", "new service", "introduce", "launch", "market entry", "product launch"],
    "Fraud": ["fraud", "scam", "fraudulent", "scammer", "phishing", "identity theft", "fraudster"],
    "Digital currency": ["bitcoin", "britcoin", "digital currency", "cbdc", "cryptocurrency", "blockchain", "crypto"],
    "IFR": [" IFR ", "interchange fee", "Interchange Fee Regulation", "interchange"],
    "Digital Wallets": ["digital wallet", "e-wallet", "mobile wallet", "payment app", "wallet service"],
    "Digital ID": ["digital ID", "identity", "authentication", "biometrics", "secure ID", " ID ", "KYC", "non-document", "digital passport", "know your customer"],
    "Commercial credit and debit Cards": ["business card", "commercial card", "corporate card"],
    "Account to Account payments (A2A)": ["A2A", "account to account", "bank transfers", "payment transfer", "interbank payments"],
    "Artificial Intelligence (AI)": [" AI ", "artificial intelligence", "machine learning", "deep learning"],
    "Big Tech": ["Apple", "Google", "Amazon", "Facebook", "Meta", "iPhone", "iPay", "IOS", "Alphabet", "Instagram", "Microsoft", "Windows", "tech giants", "digital platforms"],
    "Financial Regulators": [" ECB ", " EBA ", " ESMA ", " EIOPA ", " SEC ", "FCA", "FINRA", "ASIC", "BaFin", " MAS ", "FINMA", "FSA", "FSB", "CFTC", "NFA", "CNMV", "CONSOB", "AMF ", "AFM", "SFC", "SEBI", "CBI", "DFSA", "HKMA", "NZFMA", " BOE", "HMT", " PRA ", "regulatory authority", "supervisory body"],
    "Open Banking": ["open banking", "API ", "PSD2", "data sharing", "third-party access", "open finance"],
    "Cybersecurity": ["hack", "leak", "breach", "cyber"],
    "Legal": ["legal", " law", "court ", "attorney", "judicial", "legislation", "enacts", "tribunal", " cat ", "charges", "judge", "whistleblow", "litigat", "solicitor", "sanction"]
}



companies = {
    "Adyen": ["Adyen"],
    "Airwallex": ["Airwallex"],
    "Ascend Money": ["Ascend Money"],
    "Blue Yonder": ["Blue Yonder"],
    "Highnote": ["Highnote"],
    "Hitachi": ["Hitachi"],
    "Papaya Global": ["Papaya Global"],
    "Till Financial": ["Till Financial"],
    "additiv": ["additiv"],
    "Axis Bank": ["Axis Bank"],
    "Bravo Store Systems": ["Bravo Store Systems"],
    "Carefull": ["Carefull"],
    "Convera": ["Convera"],
    "Curios": ["Curios"],
    "Deutsche Bank": ["Deutsche Bank"],
    "Discover Global Network": ["Discover Global Network"],
    "Dock Financial": ["Dock Financial"],
    "Envestnet|Yodlee": ["Envestnet|Yodlee"],
    "Fiserv": ["Fiserv"],
    "Logic Jets": ["Logic Jets"],
    "Mogo": ["Mogo"],
    "NMI": ["NMI"],
    "Payments Europe": ["Payments Europe"],
    "Payroc": ["Payroc"],
    "RBC": ["RBC"],
    "UnionPay": ["UnionPay"],
    "Westpac": ["Westpac"],
    "WooCommerce": ["WooCommerce"],
    "xpate": ["xpate"],
    "Zilch": ["Zilch"],
    "Aero Commerce": ["Aero Commerce"],
    "Apple Wallet": ["Apple Wallet"],
    "Backbase": ["Backbase"],
    "Beyon Money": ["Beyon Money"],
    "DataVisor": ["DataVisor"],
    "D-Wave": ["D-Wave"],
    "EVO Banco": ["EVO Banco"],
    "Giesecke Devrient": ["Giesecke Devrient"],
    "Glia": ["Glia"],
    "Honor Bank": ["Honor Bank"],
    "Lloyds Bank": ["Lloyds Bank"],
    "Mastercard demonstrates": ["Mastercard demonstrates"],
    "Mastercard": ["Mastercard", "Master", "MC"],
    "NatWest": ["NatWest"],
    "NatWest enrolls": ["NatWest enrolls"],
    "Nexi Group": ["Nexi Group"],
    "OKX Wallet": ["OKX Wallet"],
    "Pleo": ["Pleo"],
    "Lopay": ["Lopay"],
    "Viva.com": ["Viva.com"],
    "Wells Fargo": ["Wells Fargo"],
    "Wise": ["Wise"],
    "Worldline": ["Worldline"],
    "Binance": ["Binance"],
    "Birake Exchange": ["Birake Exchange"],
    "BlackLine": ["BlackLine"],
    "Castles Technology": ["Castles Technology"],
    "Citi": ["Citi"],
    "Crystal Blockchain": ["Crystal Blockchain"],
    "Digiseq": ["Digiseq"],
    "EDOMx": ["EDOMx"],
    "Fime Asia": ["Fime Asia"],
    "First Orion": ["First Orion"],
    "Galileo": ["Galileo"],
    "GoDaddy": ["GoDaddy"],
    "Goldman Sachs": ["Goldman Sachs"],
    "Immutable": ["Immutable"],
    "Infinicept": ["Infinicept"],
    "kennek": ["kennek"],
    "Klarna": ["Klarna"],
    "Kushki": ["Kushki"],
    "NPCI International": ["NPCI International"],
    "Orum": ["Orum"],
    "Advent": ["Advent"],
    "Razorpay": ["Razorpay"],
    "Salt Edge": ["Salt Edge"],
    "Sila": ["Sila"],
    "STICPAY": ["STICPAY"],
    "Xsolla": ["Xsolla"],
    "Zolve": ["Zolve"],
    "Alba Bank": ["Alba Bank"],
    "BuildMyCreditScore": ["BuildMyCreditScore"],
    "Hepsipay": ["Hepsipay"],
    "HitPay": ["HitPay"],
    "Instant Financial": ["Instant Financial"],
    "J.P Morgan": ["J.P Morgan"],
    "KakaoBank": ["KakaoBank"],
    "Kraken": ["Kraken"],
    "Masabi": ["Masabi"],
    "PayStand": ["PayStand"],
    "Paytm PG": ["Paytm PG"],
    "Quant": ["Quant"],
    "Rapyd": ["Rapyd"],
    "SAP": ["SAP"],
    "Smartcash PSB": ["Smartcash PSB"],
    "Sopra": ["Sopra"],
    "Spice Money": ["Spice Money"],
    "Starling Bank": ["Starling Bank"],
    "Tebi": ["Tebi"],
    "Temenos": ["Temenos"],
    "Thomson Reuters": ["Thomson Reuters"],
    "TrustPay": ["TrustPay"],
    "Zwipe": ["Zwipe"],
    "American Express": ["American Express", "Amex"],
    "TerraPay": ["TerraPay"],
    "Beltone Capital": ["Beltone Capital"],
    "CRIF": ["CRIF"],
    "Crown Agents": ["Crown Agents"],
    "Emirates NBD": ["Emirates NBD"],
    "Flipkart": ["Flipkart"],
    "iDenfy": ["iDenfy"],
    "Jumio": ["Jumio"],
    "Komainu": ["Komainu"],
    "Metro Bank": ["Metro Bank"],
    "Optimus": ["Optimus"],
    "Pega": ["Pega"],
    "Retail Realm": ["Retail Realm"],
    "Savy": ["Savy"],
    "Socure": ["Socure"],
    "Tarabut": ["Tarabut"],
    "Trulioo": ["Trulioo"],
    "Huobi": ["Huobi"],
    "Visa": ["Visa"],
    "ABN AMRO": ["ABN AMRO"],
    "AirPlus": ["AirPlus"],
    "Bank Zero": ["Bank Zero"],
    "BTG Pactual": ["BTG Pactual"],
    "Forter": ["Forter"],
    "FullCircl": ["FullCircl"],
    "Google Wallet": ["Google Wallet"],
    "HMD Global": ["HMD Global"],
    "Ikano Bank": ["Ikano Bank"],
    "Intuit Mailchimp": ["Intuit Mailchimp"],
    "Kodex AI": ["Kodex AI"],
    "Mynt": ["Mynt"],
    "QNB Group": ["QNB Group"],
    "Rainforest": ["Rainforest"],
    "Saldo Bank": ["Saldo Bank"],
    "Swan": ["Swan"],
    "Tagit": ["Tagit"],
    "Wagestream": ["Wagestream"],
    "Aeropay": ["Aeropay"],
    "Aryza": ["Aryza"],
    "Getpaid": ["Getpaid"],
    "Pershing X": ["Pershing X"],
    "Boomi": ["Boomi"],
    "CLEAR": ["CLEAR"],
    "iwoca": ["iwoca"],
    "MeridianLink": ["MeridianLink"],
    "NAB": ["NAB"],
    "Nikulipe": ["Nikulipe"],
    "Nuvei": ["Nuvei"],
    "PayNet": ["PayNet"],
    "SaaScada": ["SaaScada"],
    "Stockpile": ["Stockpile"],
    "Tietoevry": ["Tietoevry"],
    "Western Union": ["Western Union", "WU"],
    "Apple": ["Apple", "IOS", "iPhone"],
    "BHG Financial": ["BHG Financial"],
    "Brite": ["Brite"],
    "CBA": ["CBA"],
    "Cross River": ["Cross River"],
    "Gemba Finance": ["Gemba Finance"],
    "Global Payments": ["Global Payments"],
    "Monzo": ["Monzo"],
    "Noda": ["Noda"],
    "PayPal": ["PayPal"],
    "Peach Payments": ["Peach Payments"],
    "Revolut": ["Revolut"],
    "Ripple": ["Ripple"],
    "Shift4": ["Shift4"],
    "Slice": ["Slice"],
    "Solutions by Text": ["Solutions by Text"],
    "Stitch": ["Stitch"],
    "Veriff": ["Veriff"],
    "Cobo": ["Cobo"],
    "ComplyCube": ["ComplyCube"],
    "EvenBet": ["EvenBet"],
    "Exchange Bank": ["Exchange Bank"],
    "Experian": ["Experian"],
    "Feedonomics": ["Feedonomics"],
    "Fuse": ["Fuse"],
    "Worldcoin": ["Worldcoin"],
    "Medius": ["Medius"],
    "MonetaGo": ["MonetaGo"],
    "RepRisk study": ["RepRisk study"],
    "Scalapay": ["Scalapay"],
    "SEON": ["SEON"],
    "Sintesi": ["Sintesi"],
    "Sygnum": ["Sygnum"],
    "SymphonyAI": ["SymphonyAI"],
    "Thunes": ["Thunes"],
    "Weavr": ["Weavr"],
    "BaFin": ["BaFin"],
    "Coinbase": ["Coinbase"],
    "Deluxe": ["Deluxe"],
    "Economist Impact": ["Economist Impact"],
    "Gemini": ["Gemini"],
    "LexisNexis": ["LexisNexis"],
    "Perenna": ["Perenna"],
    "Sonovate": ["Sonovate"],
    "Swoop": ["Swoop"],
    "Tap": ["Tap"],
    "UBS Asset": ["UBS Asset"],
    "UBS": ["UBS"],
    "Valu": ["Valu"],
    "Yoti": ["Yoti"],
    "Alipay+": ["Alipay+"],
    "ANZ Worldline": ["ANZ Worldline"],
    "Apron": ["Apron"],
    "Atom Bank": ["Atom Bank"],
    "Interac": ["Interac"],
    "Fireblocks": ["Fireblocks"],
    "Genpact": ["Genpact"],
    "GFT": ["GFT"],
    "MindBridge": ["MindBridge"],
    "Mirakl": ["Mirakl"],
    "NEOPAY": ["NEOPAY"],
    "Network International": ["Network International"],
    "Nexi": ["Nexi"],
    "Paygeon": ["Paygeon"],
    "Quadient": ["Quadient"],
    "Quoka": ["Quoka"],
    "REPAY": ["REPAY"],
    "Shufti": ["Shufti"],
    "Tempo France": ["Tempo France"],
    "umob": ["umob"],
    "Zumo": ["Zumo"],
    "Albo": ["Albo"],
    "CCV": ["CCV"],
    "Curve": ["Curve"],
    "Great Learning": ["Great Learning"],
    "Justt": ["Justt"],
    "Marstone": ["Marstone"],
    "NAKA": ["NAKA"],
    "NCR": ["NCR"],
    "Opus": ["Opus"],
    "Revio": ["Revio"],
    "Sift": ["Sift"],
    "Square": ["Square"],
    "Stripe": ["Stripe"],
    "Swissquote": ["Swissquote"],
    "Tuum": ["Tuum"],
    "XTM": ["XTM"],
    "Aro": ["Aro"],
    "Atomic": ["Atomic"],
    "Chase": ["Chase"],
    "Citcon": ["Citcon"],
    "Credibly": ["Credibly"],
    "GPE": ["GPE"],
    "Lloyds": ["Lloyds"],
    "MoneyGram": ["MoneyGram"],
    "Neo": ["Neo"],
    "OneID": ["OneID"],
    "Sharesies": ["Sharesies"],
    "TangoPay": ["TangoPay"],
    "Weave": ["Weave"],
    "Bank ABC": ["Bank ABC"],
    "BigCommerce": ["BigCommerce"],
    "Boku MY": ["Boku MY"],
    "Brankas": ["Brankas"],
    "Cashfree": ["Cashfree"],
    "Centiglobe": ["Centiglobe"],
    "Endoxa": ["Endoxa"],
    "FlexPoint": ["FlexPoint"],
    "Funding Societies": ["Funding Societies"],
    "Greenomy": ["Greenomy"],
    "iDEAL": ["iDEAL"],
    "iStudio": ["iStudio"],
    "Mangopay": ["Mangopay"],
    "MUFG": ["MUFG"],
    "PayBlox": ["PayBlox"],
    "Paymentology": ["Paymentology"],
    "Plum": ["Plum"],
    "Protocol Labs": ["Protocol Labs"],
    "RocketFuel": ["RocketFuel"],
    "Solaris": ["Solaris"],
    "Standard Chartered": ["Standard Chartered"],
    "TCS BaNCS": ["TCS BaNCS"],
    "Tonik": ["Tonik"],
    "TrueLayer": ["TrueLayer"],
    "UP": ["UP"],
    "Wirex": ["Wirex"],
    "XYB": ["XYB"],
    "Allied Bank": ["Allied Bank"],
    "Amazon": ["Amazon"],
    "DailyPay": ["DailyPay"],
    "EPI": ["EPI"],
    "Finastra": ["Finastra"],
    "Fusion Bank": ["Fusion Bank"],
    "Guaranty Trust": ["Guaranty Trust"],
    "KREDA": ["KREDA"],
    "Neem": ["Neem"],
    "Neonomics": ["Neonomics"],
    "PhonePe": ["PhonePe"],
    "QIB": ["QIB"],
    "Sohar": ["Sohar"],
    "Standard Life": ["Standard Life"],
    "Travelex": ["Travelex"],
    "Veem": ["Veem"],
    "Veridas": ["Veridas"],
    "Bluefin": ["Bluefin"],
    "Equifax": ["Equifax"],
    "Fujitsu": ["Fujitsu"],
    "NICE Actimize": ["NICE Actimize"],
    "Shufti Pro": ["Shufti Pro"],
    "SumUp": ["SumUp"],
    "Thales": ["Thales"],
    "Truist": ["Truist"],
    "Varo Bank": ["Varo Bank"],
    "VendorInfo": ["VendorInfo"],
    "Vero": ["Vero"],
    "CGI": ["CGI"],
    "Chipper Cash": ["Chipper Cash"],
    "CoinEx": ["CoinEx"],
    "Develo": ["Develo"],
    "eToro": ["eToro"],
    "FreedomPay": ["FreedomPay"],
    "Legit Security": ["Legit Security"],
    "Mondu": ["Mondu"],
    "Salmon": ["Salmon"],
    "Sandbox Banking": ["Sandbox Banking"],
    "Sumsub": ["Sumsub"],
    "Sybrin": ["Sybrin"],
    "True Alliance": ["True Alliance"],
    "U.S. Bank": ["U.S. Bank"],
    "360tf": ["360tf"],
    "ACI Worldwide": ["ACI Worldwide"],
    "Akoya": ["Akoya"],
    "BNY Mellon": ["BNY Mellon"],
    "Brex": ["Brex"],
    "Currencies Direct": ["Currencies Direct"],
    "Flex": ["Flex"],
    "Froda": ["Froda"],
    "HSBC": ["HSBC", "First Direct"],
    "IDEX Biometrics": ["IDEX Biometrics"],
    "InfinitePay": ["InfinitePay"],
    "Ingenico": ["Ingenico"],
    "iProov": ["iProov"],
    "Know Your Customer": ["Know Your Customer"],
    "Novo": ["Novo"],
    "Oracle": ["Oracle"],
    "PAX": ["PAX"],
    "Payoneer": ["Payoneer"],
    "SAP Fioneer": ["SAP Fioneer"],
    "Tipalti": ["Tipalti"],
    "Ant Group": ["Ant Group"],
    "Bank of America": ["Bank of America"],
    "Fabrick": ["Fabrick"],
    "FinMont": ["FinMont"],
    "HAYVN": ["HAYVN"],
    "Intesa Sanpaolo": ["Intesa Sanpaolo"],
    "Libra Internet Bank": ["Libra Internet Bank"],
    "Payflow": ["Payflow"],
    "Saxo Bank": ["Saxo Bank"],
    "SentiLink": ["SentiLink"],
    "Trade Ledger": ["Trade Ledger"],
    "Waave": ["Waave"],
    "Apiture": ["Apiture"],
    "Balance": ["Balance"],
    "Banque Delubac": ["Banque Delubac"],
    "Basikon": ["Basikon"],
    "Blackbullion": ["Blackbullion"],
    "Broadridge": ["Broadridge"],
    "Credolab": ["Credolab"],
    "EBANX": ["EBANX"],
    "EMVCo": ["EMVCo"],
    "Hapana": ["Hapana"],
    "IBM": ["IBM"],
    "Judo Bank": ["Judo Bank"],
    "Sendwave": ["Sendwave"],
    "Swift": ["Swift"],
    "Tamatem Plus": ["Tamatem Plus"],
    "Treasury Prime": ["Treasury Prime"],
    "UnionPay International": ["UnionPay International"],
    "Bitwave": ["Bitwave"],
    "BlueSnap": ["BlueSnap"],
    "CRED": ["CRED"],
    "EBA CLEARING": ["EBA CLEARING"],
    "Fipto": ["Fipto"],
    "GEP": ["GEP"],
    "Gr4vy": ["Gr4vy"],
    "IDVerse": ["IDVerse"],
    "IndusInd Bank": ["IndusInd Bank"],
    "LuLu Money": ["LuLu Money"],
    "Manigo": ["Manigo"],
    "MoneyCollect": ["MoneyCollect"],
    "NEC": ["NEC"],
    "Oobit": ["Oobit"],
    "Paysend": ["Paysend"],
    "Playtech": ["Playtech"],
    "Prelim": ["Prelim"],
    "Recharge": ["Recharge"],
    "Zoho": ["Zoho"],
    "AFSOL": ["AFSOL"],
    "Alpha Group": ["Alpha Group"],
    "Bankjoy": ["Bankjoy"],
    "Capgemini": ["Capgemini"],
    "Episode Six": ["Episode Six"],
    "Hokodo": ["Hokodo"],
    "Intuit": ["Intuit"],
    "JT Group": ["JT Group"],
    "Nethone": ["Nethone"],
    "Nubank": ["Nubank"],
    "Open Banking": ["Open Banking"],
    "Opera": ["Opera"],
    "PwC": ["PwC"],
    "SBI": ["SBI"],
    "Telegram": ["Telegram"],
    "YouAttest": ["YouAttest"],
    "BitPay": ["BitPay"],
    "Caliza": ["Caliza"],
    "Corpay": ["Corpay"],
    "CSG Forte": ["CSG Forte"],
    "Deduce": ["Deduce"],
    "Deloitte": ["Deloitte"],
    "EBL": ["EBL"],
    "Foro": ["Foro"],
    "Fountain": ["Fountain"],
    "Marygold": ["Marygold"],
    "Mibanco": ["Mibanco"],
    "Owlin": ["Owlin"],
    "Perfios": ["Perfios"],
    "RAKBANK": ["RAKBANK"],
    "Scotiabank": ["Scotiabank"],
    "VANKLIA": ["VANKLIA"],
    "BIAN": ["BIAN"],
    "Sprinque": ["Sprinque"],
    "Treyd": ["Treyd"],
    "TikTok": ["TikTok"],
    "Wintranx": ["Wintranx"],
    "Wix": ["Wix"],
    "Alibaba": ["Alibaba"],
    "Archie": ["Archie"],
    "AUB": ["AUB"],
    "Finance": ["Finance"],
    "Firework": ["Firework"],
    "Flutterwave": ["Flutterwave"],
    "Fonepay": ["Fonepay"],
    "Solid": ["Solid"],
    "Affirm": ["Affirm"],
    "Certa": ["Certa"],
    "Hyundai": ["Hyundai"],
    "Instacart": ["Instacart"],
    "JP Morgan": ["JP Morgan", "JP", "JPMorgan", "Jp"],
    "Momnt": ["Momnt"],
    "Nagad": ["Nagad"],
    "PayU": ["PayU"],
    "Upvest": ["Upvest"],
    "Zopa": ["Zopa"],
    "APEXX": ["APEXX"],
    "Arendt": ["Arendt"],
    "Central Payments": ["Central Payments"],
    "Esker": ["Esker"],
    "Idemia": ["Idemia"],
    "JCB": ["JCB"],
    "Ledger": ["Ledger"],
    "LHV Bank": ["LHV Bank"],
    "NPCI": ["NPCI"],
    "Paysafe": ["Paysafe"],
    "Strise": ["Strise"],
    "3S Money": ["3S Money"],
    "Bank of Canada": ["Bank of Canada"],
    "Blackhawk Network": ["Blackhawk Network"],
    "Bluevine": ["Bluevine"],
    "Credit Sesame": ["Credit Sesame"],
    "Crunchfish": ["Crunchfish"],
    "Factris": ["Factris"],
    "FundingShield": ["FundingShield"],
    "GXBank": ["GXBank"],
    "IDnow": ["IDnow"],
    "Kotani": ["Kotani"],
    "Ntropy": ["Ntropy"],
    "PayRetailers": ["PayRetailers"],
    "PayU India": ["PayU India"],
    "SAB": ["SAB"],
    "Tell.money": ["Tell.money"],
    "Anchor": ["Anchor"],
    "Coinstash": ["Coinstash"],
    "Complii": ["Complii"],
    "CPBank": ["CPBank"],
    "FutureBank": ["FutureBank"],
    "GenTwo": ["GenTwo"],
    "Huawei": ["Huawei"],
    "Incard": ["Incard"],
    "J.P. Morgan": ["J.P. Morgan"],
    "Paybis": ["Paybis"],
    "Pliant": ["Pliant"],
    "Qover": ["Qover"],
    "SAMA": ["SAMA"],
    "Signicat": ["Signicat"],
    "ThetaRay": ["ThetaRay"],
    "Wamo": ["Wamo"],
    "ACE Money": ["ACE Money"],
    "Acquired.com": ["Acquired.com"],
    "Arab Financial": ["Arab Financial"],
    "Astra Tech": ["Astra Tech"],
    "Banking Circle": ["Banking Circle"],
    "Bybit": ["Bybit"],
    "Cashfree Payments": ["Cashfree Payments"],
    "Clear Junction": ["Clear Junction"],
    "CyberConnect": ["CyberConnect"],
    "FedTech": ["FedTech"],
    "Gate.io": ["Gate.io"],
    "OneCard": ["OneCard"],
    "Infosys": ["Infosys"],
    "LSE Group": ["LSE Group"],
    "MIDBANK": ["MIDBANK"],
    "Morabaha Marina": ["Morabaha Marina"],
    "Paytm": ["Paytm"],
    "Pine Labs": ["Pine Labs"],
    "Safexpay": ["Safexpay"],
    "YES BANK": ["YES BANK"],
    "Alkami": ["Alkami"],
    "Atlantic": ["Atlantic"],
    "BingX": ["BingX"],
    "BlinkPay": ["BlinkPay"],
    "Circle": ["Circle"],
    "Coda": ["Coda"],
    "Conferma Pay": ["Conferma Pay"],
    "Expensify": ["Expensify"],
    "LAB Group": ["LAB Group"],
    "Nexo": ["Nexo"],
    "Rho": ["Rho"],
    "Tether": ["Tether"],
    "TrueNorth": ["TrueNorth"],
    "Vic.ai": ["Vic.ai"],
    "World Bank": ["World Bank"],
    "ZeroPay": ["ZeroPay"],
    "aiBANK": ["aiBANK"],
    "Arkose Labs": ["Arkose Labs"],
    "Bloomreach": ["Bloomreach"],
    "Google": ["Google", "Alphabet"],
    "Hallmark": ["Hallmark"],
    "Ivy": ["Ivy"],
    "OnBuy": ["OnBuy"],
    "Pelican AI": ["Pelican AI"],
    "SEPAY": ["SEPAY"],
    "TymeBank": ["TymeBank"],
    "Elavon": ["Elavon"],
    "Uplinq": ["Uplinq"],
    "X": ["X"],
    "Zil Money": ["Zil Money"],
    "AmTrust": ["AmTrust"],
    "Astra": ["Astra"],
    "Aumentum": ["Aumentum"],
    "BofA": ["BofA"],
    "CommentSold": ["CommentSold"],
    "CPI": ["CPI"],
    "Dash": ["Dash"],
    "Diebold Nixdorf": ["Diebold Nixdorf"],
    "docStribute": ["docStribute"],
    "GoCardless": ["GoCardless"],
    "Injective": ["Injective"],
    "Ivalua": ["Ivalua"],
    "Orbyt": ["Orbyt"],
    "Qarar": ["Qarar"],
    "SEBA Bank": ["SEBA Bank"],
    "VizyPay": ["VizyPay"],
    "Afreximbank": ["Afreximbank"],
    "Argus": ["Argus"],
    "BBVA": ["BBVA"],
    "BMO": ["BMO"],
    "FOMO": ["FOMO"],
    "GO Markets": ["GO Markets"],
    "Mercuryo": ["Mercuryo"],
    "Orion Innovation": ["Orion Innovation"],
    "PandaDoc": ["PandaDoc"],
    "PAPSS": ["PAPSS"],
    "PayU GPO": ["PayU GPO"],
    "Tabby": ["Tabby"],
    "Trustly": ["Trustly"],
    "Ukheshe": ["Ukheshe"],
    "VSoft": ["VSoft"],
    "WALBING": ["WALBING"],
    "Yahoo": ["Yahoo"],
    "BEST Vietnam": ["BEST Vietnam"],
    "Bitfinex": ["Bitfinex"],
    "FICO": ["FICO"],
    "FIDO Alliance": ["FIDO Alliance"],
    "FinBox": ["FinBox"],
    "GHL": ["GHL"],
    "GLN": ["GLN"],
    "Griffin": ["Griffin"],
    "Instacart files": ["Instacart files"],
    "LemFi": ["LemFi"],
    "Mangold Fondkommission": ["Mangold Fondkommission"],
    "Membrane": ["Membrane"],
    "M-Pesa": ["M-Pesa"],
    "Safaricom": ["Safaricom"],
    "Sharjah Entrepreneurship": ["Sharjah Entrepreneurship"],
    "State Bank": ["State Bank"],
    "Trulioo augments": ["Trulioo augments"],
    "USAA becomes": ["USAA becomes"],
    "Zepto": ["Zepto"],
    "Alpha Bank": ["Alpha Bank"],
    "B2C": ["B2C"],
    "Citi makes": ["Citi makes"],
    "ClearSale": ["ClearSale"],
    "FSS": ["FSS"],
    "KEPF": ["KEPF"],
    "Marqeta": ["Marqeta"],
    "N26": ["N26"],
    "Nedbank": ["Nedbank"],
    "Shopmium": ["Shopmium"],
    "Standard AI": ["Standard AI"],
    "The UAE": ["The UAE"],
    "TSG": ["TSG"],
    "Bamboo Payment": ["Bamboo Payment"],
    "ComplyAdvantage": ["ComplyAdvantage"],
    "DataArt": ["DataArt"],
    "EIF": ["EIF"],
    "Finqware": ["Finqware"],
    "Guavapay": ["Guavapay"],
    "Krakowski Bank": ["Krakowski Bank"],
    "Macau Pass": ["Macau Pass"],
    "Mast General": ["Mast General"],
    "Moneysoft": ["Moneysoft"],
    "PatientPay": ["PatientPay"],
    "Quantstamp": ["Quantstamp"],
    "ResearchAndMarkets": ["ResearchAndMarkets"],
    "Solana Pay": ["Solana Pay"],
    "SpyCloud": ["SpyCloud"],
    "Supercharge": ["Supercharge"],
    "TreasurUp": ["TreasurUp"],
    "Zorrz": ["Zorrz"],
    "Beyond": ["Beyond"],
    "Checkout.com": ["Checkout.com"],
    "Five Star": ["Five Star"],
    "FNBO": ["FNBO"],
    "IFX Payments": ["IFX Payments"],
    "Koverly": ["Koverly"],
    "Moniepoint": ["Moniepoint"],
    "Nium": ["Nium"],
    "Nomad": ["Nomad"],
    "OANDA": ["OANDA"],
    "Ramp": ["Ramp"],
    "Reserve Bank": ["Reserve Bank"],
    "OpenWallet": ["OpenWallet"],
    "True Digital": ["True Digital"],
    "Yeeld": ["Yeeld"],
    "Altum Group": ["Altum Group"],
    "ASAL Microfinance": ["ASAL Microfinance"],
    "Chinabank": ["Chinabank"],
    "Clara": ["Clara"],
    "Colendi gets": ["Colendi gets"],
    "Cynergy Bank": ["Cynergy Bank"],
    "DMALINK collaborates": ["DMALINK collaborates"],
    "Dock": ["Dock"],
    "EchoPay": ["EchoPay"],
    "Eltropy": ["Eltropy"],
    "Paradigm Sports": ["Paradigm Sports"],
    "Tamilnad Mercantile": ["Tamilnad Mercantile"],
    "Tap-to": ["Tap-to"],
    "Tbi Bank": ["Tbi Bank"],
    "Teamwork Commerce": ["Teamwork Commerce"],
    "Thales empowers": ["Thales empowers"],
    "TreviPay": ["TreviPay"],
    "Vista": ["Vista"],
    "VU": ["VU"],
    "Atome Financial": ["Atome Financial"],
    "Cambodia": ["Cambodia"],
    "DBS Bank": ["DBS Bank"],
    "MOIN": ["MOIN"],
    "New UK": ["New UK"],
    "OMNIA": ["OMNIA"],
    "Reltime": ["Reltime"],
    "Newstore": ["Newstore"],
    "Alpaca": ["Alpaca"],
    "Hifi": ["Hifi"],
    "Credova": ["Credova"],
    "Numis": ["Numis"],
    "Paydora Finance": ["Paydora Finance"],
    "Plaid": ["Plaid"],
    "Triple-A": ["Triple-A"],
    "Xero": ["Xero"],
    "Lazada": ["Lazada"],
    "Currencycloud": ["Currencycloud"],
    "Ordo": ["Ordo"],
    "US Discover": ["US Discover"],
    "Satispay": ["Satispay"],
    "Snowdrop Solutions": ["Snowdrop Solutions"],
    "Skytef": ["Skytef"],
    "Lumin Digital": ["Lumin Digital"],
    "nCino": ["nCino"],
    "Bizom": ["Bizom"],
    "P12": ["P12"],
    "Fibe": ["Fibe"],
    "Versana": ["Versana"],
    "Global Anti-Scam Alliance": ["Global Anti-Scam Alliance"],
    "Unlimit": ["Unlimit"],
    "finbotsAI": ["finbotsAI"],
    "Paze": ["Paze"],
    "GreenSky": ["GreenSky"],
    "Payment Visor": ["Payment Visor"],
    "Fortress Trust": ["Fortress Trust"],
    "Mambu": ["Mambu"],
    "HKEX Synapse": ["HKEX Synapse"],
    "GCash": ["GCash"],
    "Securities Services": ["Securities Services"],
    "Superbank": ["Superbank"],
    "BCM": ["BCM"],
    "Worldpay": ["Worldpay"],
    "Microsoft": ["Microsoft", "Windows"],
    "NSDL": ["NSDL"],
    "ONESOURCE": ["ONESOURCE"],
    "TripLink": ["TripLink"],
    "Bancolombia": ["Bancolombia"],
    "NomadRem": ["NomadRem"],
    "NextWealth": ["NextWealth"],
    "Peacock": ["Peacock"],
    "AMLYZE": ["AMLYZE"],
    "eCU": ["eCU"],
    "FLOOSS": ["FLOOSS"],
    "ibanXS": ["ibanXS"],
    "KuCoin": ["KuCoin"],
    "Motive Partners": ["Motive Partners"],
    "Programme": ["Programme"],
    "Bank": ["Bank"],
    "Pay": ["Pay"],
    "Qlik": ["Qlik"],
    "ECPay": ["ECPay"],
    "Lucca": ["Lucca"],
    "Veefin Solution": ["Veefin Solution"],
    "Keebo": ["Keebo"],
    "UBank": ["UBank"],
    "Integrity": ["Integrity"],
    "Marketplace": ["Marketplace"],
    "Shopify": ["Shopify"],
    "Trovata": ["Trovata"],
    "Aircash": ["Aircash"],
    "Paywatch": ["Paywatch"],
    "TX Ventures": ["TX Ventures"],
    "Green Dot": ["Green Dot"],
    "Cable": ["Cable"],
    "NextGen": ["NextGen"],
    "paymints.io": ["paymints.io"],
    "Tickets Travel Network": ["Tickets Travel Network"],
    "Paymentwall": ["Paymentwall"],
    "SoftBank": ["SoftBank"],
    "SpotOn": ["SpotOn"],
    "Pidgin": ["Pidgin"],
    "BlackRock": ["BlackRock"],
    "Tesselate": ["Tesselate"],
    "SeaPay": ["SeaPay"],
    "Fourthline": ["Fourthline"],
    "Access Africa": ["Access Africa"],
    "Expel": ["Expel"],
    "Comma": ["Comma"],
    "Aliaswire": ["Aliaswire"],
    "L&C": ["L&C"],
    "Sage": ["Sage"],
    "Zero Hash": ["Zero Hash"],
    "Kamma": ["Kamma"],
    "BlockFold": ["BlockFold"],
    "Thought Machine": ["Thought Machine"],
    "Havas": ["Havas"],
    "Alipay": ["Alipay"],
    "Codebase": ["Codebase"],
    "Aconomy": ["Aconomy"],
    "nTokens": ["nTokens"],
    "Onfido": ["Onfido"],
    "dLocal": ["dLocal"],
    "Jack Henry": ["Jack Henry"],
    "Clip Money": ["Clip Money"],
    "Checkmarx": ["Checkmarx"],
    "QRails": ["QRails"],
    "Plend": ["Plend"],
    "CommEX": ["CommEX"],
    "Cash App Pay": ["Cash App Pay"],
    "Afterpay": ["Afterpay"],
    "Netcetera": ["Netcetera"],
    "Datacap": ["Datacap"],
    "ABHI": ["ABHI"],
    "YellowPepper": ["YellowPepper"],
    "Konsentus": ["Konsentus"],
    "Zimpler": ["Zimpler"],
    "Droit": ["Droit"],
    "in3": ["in3"],
    "VTEX": ["VTEX"],
    "Tuily": ["Tuily"],
    "Consensys": ["Consensys"],
    "AvecPay": ["AvecPay"],
    "Give Lively": ["Give Lively"],
    "Starfish": ["Starfish"],
    "Standard Bank": ["Standard Bank"],
    "Onramper": ["Onramper"],
    "Fasset": ["Fasset"],
    "Synapsify": ["Synapsify"],
    "Anthropic": ["Anthropic"],
    "BrankieOne": ["BrankieOne"],
    "Corvallis": ["Corvallis"],
    "WeBank": ["WeBank"],
    "BetterNow": ["BetterNow"],
    "Mascap": ["Mascap"],
    "Moneyhub": ["Moneyhub"],
    "Mitek": ["Mitek"],
    "Asset Reality": ["Asset Reality"],
    "GoTyme": ["GoTyme"],
    "Newton Global": ["Newton Global"],
    "Intel": ["Intel"],
    "Infineon": ["Infineon"],
    "CRV": ["CRV"],
    "Regula": ["Regula"],
    "Ebury": ["Ebury"],
    "Envestnet": ["Envestnet"],
    "Yodlee": ["Yodlee", "Envestnet|Yodlee"],
    "Transact": ["Transact"],
    "KL HI-TECH": ["KL HI-TECH"],
    "Diggercard": ["Diggercard"],
    "Ping": ["Ping"],
    "Airbnb": ["Airbnb"],
    "dtcpay": ["dtcpay"],
    "MIND DXM": ["MIND DXM"],
    "Hilbert": ["Hilbert"],
    "MiCA": ["MiCA"],
    "Saxo": ["Saxo"],
    "Greenlight": ["Greenlight"],
    "Numeral": ["Numeral"],
    "Circulo de Credito": ["Circulo de Credito"],
    "Nova Credit": ["Nova Credit"],
    "Gilded": ["Gilded"],
    "BigTime": ["BigTime"],
    "Datos Insights": ["Datos Insights"],
    "Taurus": ["Taurus"],
    "Kestrl": ["Kestrl"],
    "Nimo": ["Nimo"],
    "Endava": ["Endava"],
    "SurePay": ["SurePay"],
    "Colony": ["Colony"],
    "Startselect": ["Startselect"],
    "RedWeek": ["RedWeek"],
    "Public": ["Public"],
    "Fime": ["Fime"],
    "Cobase": ["Cobase"],
    "Panacea": ["Panacea"],
    "Honey Badger": ["Honey Badger"],
    "Verifi": ["Verifi"],
    "BVNK": ["BVNK"],
    "Celo": ["Celo"],
    "Clearspeed": ["Clearspeed"],
    "Petit Bateau": ["Petit Bateau"],
    "Auctionet": ["Auctionet"],
    "ekko": ["ekko"],
    "Bridge": ["Bridge"],
    "Branch": ["Branch"],
    "Cybernetica": ["Cybernetica"],
    "Incode": ["Incode"],
    "Sardine": ["Sardine"],
    "BankAxept": ["BankAxept"],
    "Form3": ["Form3"],
    "Rongbao": ["Rongbao"],
    "NIPL": ["NIPL"],
    "Inpay": ["Inpay"],
    "Trust": ["Trust"],
    "Lewis & Clark": ["Lewis & Clark"],
    "Booking": ["Booking"],
    "Bankify": ["Bankify"],
    "Salesforce": ["Salesforce"],
    "KredX": ["KredX"],
    "Meta": ["Meta", "Facebook", "Instagram"],
    "AML": ["AML"],
    "Fenergo": ["Fenergo"],
    "Waddle": ["Waddle"],
    "Boost": ["Boost"],
    "Bridgewise": ["Bridgewise"],
    "Airtel": ["Airtel"],
    "PAYONE": ["PAYONE"],
    "Kriya": ["Kriya"],
    "Eightcap": ["Eightcap"],
    "LISNR": ["LISNR"],
    "Tata": ["Tata"],
    "Icon": ["Icon"],
    "Yapily": ["Yapily"],
    "HyperPay": ["HyperPay"],
    "CommercePro": ["CommercePro"],
    "Cloud Finance": ["Cloud Finance"],
    "Colossos": ["Colossos"],
    "DECTA": ["DECTA"],
    "Solana": ["Solana"],
    "Investified": ["Investified"],
    "MIntegrity": ["MIntegrity"],
    "Eurogiro": ["Eurogiro"],
    "Friday": ["Friday"],
    "Moldur": ["Moldur"],
    "Polygon CDK": ["Polygon CDK"],
    "Alfalah": ["Alfalah"],
    "Jamboree": ["Jamboree"],
    "Altalix": ["Altalix"],
    "Komgo": ["Komgo"],
    "Tookitaki": ["Tookitaki"],
    "Mercado Pago": ["Mercado Pago"],
    "Mobily": ["Mobily"],
    "Inlogik": ["Inlogik"],
    "functionality": ["functionality"],
    "Truecaller": ["Truecaller"],
    "Capital": ["Capital"],
    "PayMate": ["PayMate"],
    "Britannia": ["Britannia"],
    "RADD": ["RADD"],
    "IDB": ["IDB"],
    "Nu": ["Nu"],
    "Venmo": ["Venmo"],
    "Everset": ["Everset"],
    "Surecomp": ["Surecomp"],
    "Buckaroo": ["Buckaroo"],
    "PayShap": ["PayShap"],
    "Kiwibank": ["Kiwibank"],
    "PremiumPay": ["PremiumPay"],
    "Shredder": ["Shredder"],
    "KyckGlobal": ["KyckGlobal"],
    "Pegasystems": ["Pegasystems"],
    "Commusoft": ["Commusoft"],
    "C6": ["C6"],
    "Tink": ["Tink"],
    "Moneythor": ["Moneythor"],
    "Biz2X": ["Biz2X"],
    "Clear Lake": ["Clear Lake"],
    "StarCompliance": ["StarCompliance"],
    "Notabene": ["Notabene"],
    "Denario": ["Denario"],
    "Diamond Trust": ["Diamond Trust"],
    "Techcombank": ["Techcombank"],
    "Vakıfbank": ["Vakıfbank"],
    "IIFL": ["IIFL"],
    "Crosskey": ["Crosskey"],
    "Ingiz": ["Ingiz"],
    "NymCard": ["NymCard"],
    "Orange Money": ["Orange Money"],
    "Rextie": ["Rextie"],
    "Giftbit": ["Giftbit"],
    "Sergel": ["Sergel"],
    "SavvyMoney": ["SavvyMoney"],
    "inDrive": ["inDrive"],
    "Avalara": ["Avalara"],
    "Sileon": ["Sileon"],
    "Kopo": ["Kopo"],
    "OZ": ["OZ"],
    "Ncontracts": ["Ncontracts"],
    "Feedzai": ["Feedzai"],
    "ZooPay": ["ZooPay"],
    "TransferMate": ["TransferMate"],
    "Jocata": ["Jocata"],
    "NovoPayment": ["NovoPayment"],
    "Checkout": ["Checkout"],
    "Qashio": ["Qashio"],
    "Drex": ["Drex"],
    "GNB": ["GNB"],
}

countries = {
    "Afghanistan": ["Afghanistan"],
    "Albania": ["Albania"],
    "Algeria": ["Algeria"],
    "Andorra": ["Andorra"],
    "Angola": ["Angola"],
    "Antigua and Barbuda": ["Antigua and Barbuda"],
    "Argentina": ["Argentina"],
    "Armenia": ["Armenia"],
    "Australia": ["Australia"],
    "Austria": ["Austria"],
    "Azerbaijan": ["Azerbaijan"],
    "Bahamas": ["Bahamas"],
    "Bahrain": ["Bahrain"],
    "Bangladesh": ["Bangladesh"],
    "Barbados": ["Barbados"],
    "Belarus": ["Belarus"],
    "Belgium": ["Belgium"],
    "Belize": ["Belize"],
    "Benin": ["Benin"],
    "Bhutan": ["Bhutan"],
    "Bolivia": ["Bolivia"],
    "Bosnia and Herzegovina": ["Bosnia and Herzegovina"],
    "Botswana": ["Botswana"],
    "Brazil": ["Brazil"],
    "Brunei": ["Brunei"],
    "Bulgaria": ["Bulgaria"],
    "Burkina Faso": ["Burkina Faso"],
    "Burundi": ["Burundi"],
    "Cabo Verde": ["Cabo Verde"],
    "Cambodia": ["Cambodia"],
    "Cameroon": ["Cameroon"],
    "Canada": ["Canada"],
    "Central African Republic": ["Central African Republic"],
    "Chad": ["Chad"],
    "Chile": ["Chile"],
    "China": ["China"],
    "Colombia": ["Colombia"],
    "Comoros": ["Comoros"],
    "Congo": ["Congo"],
    "Democratic Republic of the Congo": ["Democratic Republic of the Congo"],
    "Costa Rica": ["Costa Rica"],
    "Cote d'Ivoire": ["Cote d'Ivoire"],
    "Croatia": ["Croatia"],
    "Cuba": ["Cuba"],
    "Cyprus": ["Cyprus"],
    "Czech Republic": ["Czech Republic"],
    "Denmark": ["Denmark"],
    "Djibouti": ["Djibouti"],
    "Dominica": ["Dominica"],
    "Dominican Republic": ["Dominican Republic"],
    "East Timor": ["East Timor"],
    "Ecuador": ["Ecuador"],
    "Egypt": ["Egypt"],
    "El Salvador": ["El Salvador"],
    "Equatorial Guinea": ["Equatorial Guinea"],
    "Eritrea": ["Eritrea"],
    "Estonia": ["Estonia"],
    "Ethiopia": ["Ethiopia"],
    "Europe": ["Albania", "Andorra", "Austria", "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Cyprus", "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Kosovo", "Latvia", "Liechtenstein", "Lithuania", "Luxembourg", "Malta", "Moldova", "Monaco", "Montenegro", "Netherlands", "North Macedonia", "Norway", "Poland", "Portugal", "Romania", "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland", "Ukraine", "United Kingdom", "Vatican City (Holy See)", "European Union (EU)", "European Central Bank (ECB)", "European Banking Authority (EBA)", "European Securities and Markets Authority (ESMA)", "European Insurance and Occupational Pensions Authority (EIOPA)", "European Commission", "European Parliament", "Council of the European Union", "European Council", "EC"],
    "Fiji": ["Fiji"],
    "Finland": ["Finland"],
    "France": ["France"],
    "Gabon": ["Gabon"],
    "Gambia": ["Gambia"],
    "Georgia": ["Georgia"],
    "Germany": ["Germany"],
    "Ghana": ["Ghana"],
    "Greece": ["Greece"],
    "Grenada": ["Grenada"],
    "Guatemala": ["Guatemala"],
    "Guinea": ["Guinea"],
    "Guinea-Bissau": ["Guinea-Bissau"],
    "Guyana": ["Guyana"],
    "Haiti": ["Haiti"],
    "Honduras": ["Honduras"],
    "Hungary": ["Hungary"],
    "Iceland": ["Iceland"],
    "India": ["India"],
    "Indonesia": ["Indonesia"],
    "Iran": ["Iran"],
    "Iraq": ["Iraq"],
    "Ireland": ["Ireland"],
    "Israel": ["Israel"],
    "Italy": ["Italy"],
    "Jamaica": ["Jamaica"],
    "Japan": ["Japan"],
    "Jordan": ["Jordan"],
    "Kazakhstan": ["Kazakhstan"],
    "Kenya": ["Kenya"],
    "Kiribati": ["Kiribati"],
    "Kuwait": ["Kuwait"],
    "Kyrgyzstan": ["Kyrgyzstan"],
    "Laos": ["Laos"],
    "Latvia": ["Latvia"],
    "Lebanon": ["Lebanon"],
    "Lesotho": ["Lesotho"],
    "Liberia": ["Liberia"],
    "Libya": ["Libya"],
    "Liechtenstein": ["Liechtenstein"],
    "Lithuania": ["Lithuania"],
    "Luxembourg": ["Luxembourg"],
    "Madagascar": ["Madagascar"],
    "Malawi": ["Malawi"],
    "Malaysia": ["Malaysia"],
    "Maldives": ["Maldives"],
    "Mali": ["Mali"],
    "Malta": ["Malta"],
    "Marshall Islands": ["Marshall Islands"],
    "Mauritania": ["Mauritania"],
    "Mauritius": ["Mauritius"],
    "Mexico": ["Mexico"],
    "Micronesia": ["Micronesia"],
    "Moldova": ["Moldova"],
    "Monaco": ["Monaco"],
    "Mongolia": ["Mongolia"],
    "Montenegro": ["Montenegro"],
    "Morocco": ["Morocco"],
    "Mozambique": ["Mozambique"],
    "Myanmar (Burma)": ["Myanmar (Burma)"],
    "Namibia": ["Namibia"],
    "Nauru": ["Nauru"],
    "Nepal": ["Nepal"],
    "Netherlands": ["Netherlands"],
    "New Zealand": ["New Zealand"],
    "Nicaragua": ["Nicaragua"],
    "Niger": ["Niger"],
    "Nigeria": ["Nigeria"],
    "North Korea": ["North Korea"],
    "Norway": ["Norway"],
    "Oman": ["Oman"],
    "Pakistan": ["Pakistan"],
    "Palau": ["Palau"],
    "Palestine": ["Palestine"],
    "Panama": ["Panama"],
    "Papua New Guinea": ["Papua New Guinea"],
    "Paraguay": ["Paraguay"],
    "Peru": ["Peru"],
    "Philippines": ["Philippines"],
    "Poland": ["Poland"],
    "Portugal": ["Portugal"],
    "Qatar": ["Qatar"],
    "Romania": ["Romania"],
    "Russia": ["Russia"],
    "Rwanda": ["Rwanda"],
    "Saint Kitts and Nevis": ["Saint Kitts and Nevis"],
    "Saint Lucia": ["Saint Lucia"],
    "Saint Vincent and the Grenadines": ["Saint Vincent and the Grenadines"],
    "Samoa": ["Samoa"],
    "San Marino": ["San Marino"],
    "Sao Tome and Principe": ["Sao Tome and Principe"],
    "Saudi Arabia": ["Saudi Arabia"],
    "Senegal": ["Senegal"],
    "Serbia": ["Serbia"],
    "Seychelles": ["Seychelles"],
    "Sierra Leone": ["Sierra Leone"],
    "Singapore": ["Singapore"],
    "Slovakia": ["Slovakia"],
    "Slovenia": ["Slovenia"],
    "Solomon Islands": ["Solomon Islands"],
    "Somalia": ["Somalia"],
    "South Africa": ["South Africa"],
    "South Korea": ["South Korea"],
    "South Sudan": ["South Sudan"],
    "Spain": ["Spain"],
    "Sri Lanka": ["Sri Lanka"],
    "Sudan": ["Sudan"],
    "Suriname": ["Suriname"],
    "Swaziland": ["Swaziland"],
    "Sweden": ["Sweden"],
    "Switzerland": ["Switzerland"],
    "Syria": ["Syria"],
    "Tajikistan": ["Tajikistan"],
    "Tanzania": ["Tanzania"],
    "Thailand": ["Thailand"],
    "Timor-Leste": ["Timor-Leste"],
    "Togo": ["Togo"],
    "Tonga": ["Tonga"],
    "Trinidad and Tobago": ["Trinidad and Tobago"],
    "Tunisia": ["Tunisia"],
    "Turkey": ["Turkey"],
    "Turkmenistan": ["Turkmenistan"],
    "Tuvalu": ["Tuvalu"],
    "Uganda": ["Uganda"],
    "Ukraine": ["Ukraine"],
    "United Arab Emirates": ["United Arab Emirates"],
    "United Kingdom": ["United Kingdom", "UK", "GB", "Great Britain", "England", "Scotland", "Wales", "NI", "Northern Ireland", "London", "the city", "FCA", "PSR", "HMT"],
    "United States": ["United States"],
    "Uruguay": ["Uruguay"],
    "Uzbekistan": ["Uzbekistan"],
    "Vanuatu": ["Vanuatu"],
    "Vatican City": ["Vatican City"],
    "Venezuela": ["Venezuela"],
    "Vietnam": ["Vietnam"],
    "Yemen": ["Yemen"],
    "Zambia": ["Zambia"],
    "Zimbabwe": ["Zimbabwe"]
}

firm_categories = {
    "Adyen": ["Payment Processor" "Payment Gateway" "Acquirer"],
    "Airwallex": ["Payment Processor" "Payment Gateway" "acquirer"],
    "Ascend Money": ["Payment Processor"],
    "Blue Yonder": ["Technology Company"],
    "Highnote": ["Other"],
    "Hitachi Payment": ["Payment Processor"],
    "Papaya Global": ["Payment Gateway"],
    "Till Financial": ["Other"],
    "additiv": ["Technology Company"],
    "Axis Bank": ["Issuing Bank" "Acquiring Bank"],
    "Block": ["Payment Processor" "Payment Gateway" "BigTech"],
    "Bravo Store Systems": ["POS system"],
    "Carefull": ["Other"],
    "Convera": ["Other"],
    "Curios": ["Other"],
    "Deutsche Bank": ["Issuing Bank" "Acquiring Bank"],
    "Discover Global Network": ["Card Scheme"],
    "Dock Financial": ["Other"],
    "Envestnet|Yodlee": ["PISP" "Technology Company"],
    "Fiserv": ["Payment Processor" "Payment Gateway"],
    "Logic Jets": ["Other"],
    "Mogo": ["Other"],
    "NMI": ["Payment Gateway" "Payment Processor"],
    "Payments Europe": ["Other"],
    "Payroc": ["Payment Processor" "Payment Gateway"],
    "RBC": ["Issuing Bank" "Acquiring Bank"],
    "UnionPay": ["Card Scheme" "Issuer" "Acquirer"],
    "Westpac": ["Issuing Bank" "Acquiring Bank"],
    "WooCommerce": ["Payment Gateway" "Technology Company"],
    "xpate": ["Payment Processor"],
    "Zilch": ["PISP" "Payment Processor"],
    "Aero Commerce": ["Payment Gateway"],
    "Backbase": ["Technology Company"],
    "Beyon Money": ["Other"],
    "DataVisor": ["Technology Company"],
    "D-Wave": ["Technology Company"],
    "EVO Banco": ["Issuing Bank" "Acquiring Bank"],
    "Giesecke Devrient": ["Technology Company"],
    "Glia": ["Technology Company"],
    "Honor Bank": ["Issuing Bank"],
    "Lloyds Bank": ["Issuing Bank" "Acquiring Bank"],
    "Mastercard demonstrates": ["Card Scheme"],
    "Mastercard": ["Card Scheme" "Issuer" "Acquirer"],
    "NatWest": ["Issuer" "Acquirer" "Payment Processor"],
    "NatWest enrolls": ["Issuing Bank" "Acquiring Bank"],
    "Nexi Group": ["Payment Processor"],
    "OKX Wallet": ["Other"],
    "Pleo": ["Payment Processor" "Payment Gateway"],
    "Lopay": ["Payment Gateway"],
    "Viva.com": ["Payment Gateway"],
    "Wells Fargo": ["Acquirer" "Issuer" "Payment Processor"],
    "Wise": ["PISP" "Payment Processor"],
    "Worldline": ["Payment Processor" "Payment Gateway"],
    "Binance": ["Other"],
    "Birake Exchange": ["Other"],
    "BlackLine": ["Technology Company"],
    "Castles Technology": ["POS system"],
    "Citi": ["Issuing Bank" "Acquiring Bank"],
    "Crystal Blockchain": ["Technology Company"],
    "Digiseq": ["Technology Company"],
    "EDOMx": ["Payment Processor" "Payment Gateway" "Acquirer"],
    "Fime Asia": ["Technology Company"],
    "First Orion": ["Technology Company"],
    "Galileo": ["Payment Processor" "Payment Gateway" "Acquirer"],
    "GoDaddy": ["Technology Company"],
    "Goldman Sachs": ["Issuing Bank" "Acquiring Bank"],
    "Immutable": ["Other"],
    "Infinicept": ["Technology Company"],
    "kennek": ["Other"],
    "Klarna": ["Other"],
    "Kushki": ["Payment Processor" "Payment Gateway"],
    "NPCI International": ["Other"],
    "Orum": ["Other"],
    "Advent": ["Other"],
    "Razorpay": ["Payment Processor" "Payment Gateway"],
    "Salt Edge": ["Technology Company"],
    "Sila": ["Other"],
    "STICPAY": ["Payment Processor" "Payment Gateway" "Acquirer"],
    "Xsolla": ["Technology Company"],
    "Zolve": ["Other"],
    "Alba Bank": ["Issuing Bank" "Acquiring Bank"],
    "BuildMyCreditScore": ["Other"],
    "Hepsipay": ["Payment Processor" "Payment Gateway"],
    "HitPay": ["Payment Processor" "Payment Gateway"],
    "Instant Financial": ["Other"],
    "J.P Morgan": ["Issuing Bank" "Acquiring Bank"],
    "KakaoBank": ["Issuing Bank" "Acquiring Bank"],
    "Kraken": ["Other"],
    "Masabi": ["Technology Company"],
    "PayStand": ["PayStand"],
    "Paytm PG": ["Payment Processor" "Payment Gateway"],
    "Quant": ["Technology Company"],
    "Rapyd": ["Payment Processor" "Payment Gateway" "Acquirer"],
    "SAP": ["SAP"],
    "Smartcash PSB": ["Other"],
    "Sopra": ["Technology Company"],
    "Spice Money": ["Payment Processor" "Payment Gateway"],
    "Starling Bank": ["Issuing Bank" "Acquiring Bank"],
    "Tebi": ["Payment Processor" "Payment Gateway"],
    "Temenos": ["Temenos"],
    "Thomson Reuters": ["Other"],
    "TrustPay": ["Payment Processor" "Payment Gateway"],
    "Zwipe": ["Technology Company"],
    "American Express": ["Card Scheme"],
    "TerraPay": ["TerraPay"],
    "Beltone Capital": ["Other"],
    "CRIF": ["Technology Company"],
    "Crown Agents": ["Other"],
    "Emirates NBD": ["Issuing Bank" "Acquiring Bank"],
    "Flipkart": ["Other"],
    "iDenfy": ["Technology Company"],
    "Jumio": ["Technology Company"],
    "Komainu": ["Technology Company"],
    "Metro Bank": ["Issuing Bank" "Acquiring Bank"],
    "Optimus": ["Other"],
    "Pega": ["Technology Company"],
    "Retail Realm": ["Technology Company"],
    "Savy": ["Other"],
    "Socure": ["Technology Company"],
    "Tarabut": ["Other"],
    "Trulioo": ["Technology Company"],
    "Huobi": ["Other"],
    "Visa": ["Visa"],
    "ABN AMRO": ["Issuing Bank" "Acquiring Bank"],
    "AirPlus": ["Payment Processor" "Payment Gateway"],
    "Bank Zero": ["Other"],
    "BTG Pactual": ["Other"],
    "Forter": ["Technology Company"],
    "FullCircl": ["Other"],
    "Google Wallet": ["Technology Company"],
    "HMD Global": ["Technology Company"],
    "Ikano Bank": ["Issuing Bank" "Acquiring Bank"],
    "Intuit Mailchimp": ["Technology Company"],
    "Kodex AI": ["Technology Company"],
    "Mynt": ["Other"],
    "QNB Group": ["Other"],
    "Rainforest": ["Technology Company"],
    "Saldo Bank": ["Issuing Bank" "Acquiring Bank"],
    "Swan": ["Other"],
    "Tagit": ["Technology Company"],
    "Wagestream": ["Other"],
    "Aeropay": ["Payment Processor" "Payment Gateway"],
    "Aryza": ["Technology Company"],
    "Getpaid": ["Other"],
    "Pershing X": ["Technology Company"],
    "Boomi": ["Technology Company"],
    "CLEAR": ["Technology Company"],
    "iwoca": ["Technology Company"],
    "MeridianLink": ["Technology Company"],
    "NAB": ["Issuing Bank" "Acquiring Bank"],
    "Nikulipe": ["Other"],
    "Nuvei": ["Payment Processor" "Payment Gateway" "Acquirer"],
    "PayNet": ["Payment Processor" "Payment Gateway"],
    "SaaScada": ["Other"],
    "Stockpile": ["Other"],
    "Tietoevry": ["Technology Company"],
    "Western Union": ["Payment Processor" "Payment Gateway" "Acquirer"],
    "Apple": ["Technology Company"],
    "BHG Financial": ["Other"],
    "Brite": ["Technology Company"],
    "CBA": ["Issuing Bank" "Acquiring Bank"],
    "Cross River": ["Other"],
    "Gemba Finance": ["Other"],
    "Global Payments": ["Payment Processor" "Payment Gateway" "Acquirer"],
    "Monzo": ["Issuing Bank" "Acquiring Bank"],
    "Noda": ["Technology Company"],
    "PayPal": ["Payment Processor" "Payment Gateway" "Acquirer"],
    "Peach Payments": ["Payment Processor" "Payment Gateway"],
    "Revolut": ["Payment Processor" "Payment Gateway"],
    "Ripple": ["Other"],
    "Shift4": ["Payment Processor" "Payment Gateway"],
    "Slice": ["Other"],
    "Solutions by Text": ["Technology Company"],
    "Stitch": ["Technology Company"],
    "Veriff": ["Technology Company"],
    "Cobo": ["Other"],
    "ComplyCube": ["Technology Company"],
    "EvenBet": ["Technology Company"],
    "Exchange Bank": ["Issuing Bank" "Acquiring Bank"],
    "Experian": ["Technology Company"],
    "Feedonomics": ["Technology Company"],
    "Fuse": ["Other"],
    "Worldcoin": ["Technology Company"],
    "Medius": ["Technology Company"],
    "MonetaGo": ["Technology Company"],
    "RepRisk study": ["Technology Company"],
    "Scalapay": ["Payment Processor" "Payment Gateway"],
    "SEON": ["Technology Company"],
    "Sintesi": ["Other"],
    "Sygnum": ["Other"],
    "SymphonyAI": ["Technology Company"],
    "Thunes": ["Technology Company"],
    "Weavr": ["Technology Company"],
    "BaFin": ["Other"],
    "Coinbase": ["Other"],
    "Deluxe": ["Other"],
    "Economist Impact": ["Other"],
    "Gemini": ["Other"],
    "LexisNexis": ["Technology Company"],
    "Perenna": ["Technology Company"],
    "Sonovate": ["Technology Company"],
    "Swoop": ["Other"],
    "Tap": ["Technology Company"],
    "UBS Asset": ["Other"],
    "UBS": ["Issuing Bank" "Acquiring Bank"],
    "Valu": ["Other"],
    "Yoti": ["Digital ID"],
    "Alipay+": ["Payment Processor" "Payment Gateway"],
    "ANZ Worldline": ["Payment Processor" "Payment Gateway"],
    "Apron": ["Other"],
    "Atom Bank": ["Issuing Bank" "Acquiring Bank"],
    "Interac": ["Payment Processor" "Payment Gateway"],
    "Fireblocks": ["Technology Company"],
    "Genpact": ["Technology Company"],
    "GFT": ["Other"],
    "MindBridge": ["Technology Company"],
    "Mirakl": ["Technology Company"],
    "NEOPAY": ["Technology Company"],
    "Network International": ["Payment Processor" "Payment Gateway" "Acquirer"],
    "Nexi": ["Payment Processor" "Payment Gateway" "Acquirer"],
    "Paygeon": ["Payment Processor" "Payment Gateway"],
    "Quadient": ["Other"],
    "Quoka": ["Other"],
    "REPAY": ["Payment Processor" "Payment Gateway"],
    "Shufti": ["Technology Company"],
    "Tempo France": ["Technology Company"],
    "umob": ["Other"],
    "Zumo": ["Other"],
    "Albo": ["Payment Processor" "Payment Gateway"],
    "CCV": ["Other"],
    "Curve": ["Payment Processor" "Payment Gateway"],
    "Great Learning": ["Other"],
    "Justt": ["Other"],
    "Marstone": ["Technology Company"],
    "NAKA": ["Other"],
    "NCR": ["Technology Company"],
    "Opus": ["Technology Company"],
    "Revio": ["Other"],
    "Sift": ["Technology Company"],
    "Square": ["Payment Processor" "Payment Gateway"],
    "Stripe": ["Payment Processor" "Payment Gateway"],
    "Swissquote": ["Other"],
    "Tuum": ["Other"],
    "XTM": ["Payment Processor" "Payment Gateway"],
    "Aro": ["Other"],
    "Atomic": ["Other"],
    "Chase": ["Issuing Bank" "Acquiring Bank"],
    "Citcon": ["Payment Processor" "Payment Gateway"],
    "Credibly": ["Other"],
    "GPE": ["Other"],
    "Lloyds": ["Issuing Bank" "Acquiring Bank"],
    "MoneyGram": ["Payment Processor" "Payment Gateway" "Acquirer"],
    "Neo": ["Other"],
    "OneID": ["Digital ID"],
    "Sharesies": ["Technology Company"],
    "TangoPay": ["Other"],
    "Weave": ["Other"],
    "Bank ABC": ["Issuing Bank" "Acquiring Bank"],
    "BigCommerce": ["Technology Company"],
    "Boku MY": ["Technology Company"],
    "Brankas": ["Technology Company"],
    "Cashfree": ["Payment Processor" "Payment Gateway"],
    "Centiglobe": ["Other"],
    "Endoxa": ["Other"],
    "FlexPoint": ["Other"],
    "Funding Societies": ["Other"],
    "Greenomy": ["Other"],
    "iDEAL": ["Payment Processor" "Payment Gateway"],
    "iStudio": ["Technology Company"],
    "Mangopay": ["Payment Processor" "Payment Gateway"],
    "MUFG": ["Issuing Bank" "Acquiring Bank"],
    "PayBlox": ["Payment Processor" "Payment Gateway"],
    "Paymentology": ["Payment Processor" "Payment Gateway"],
    "Plum": ["Payment Processor" "Payment Gateway"],
    "Protocol Labs": ["Technology Company"],
    "RocketFuel": ["Payment Processor" "Payment Gateway"],
    "Solaris": ["Other"],
    "Standard Chartered": ["Issuing Bank" "Acquiring Bank"],
    "TCS BaNCS": ["Technology Company"],
    "Tonik": ["Other"],
    "TrueLayer": ["Payment Processor" "Payment Gateway"],
    "UP": ["Other"],
    "Wirex": ["Payment Processor" "Payment Gateway"],
    "XYB": ["Other"],
    "Allied Bank": ["Issuing Bank" "Acquiring Bank"],
    "Amazon": ["Technology Company"],
    "DailyPay": ["Technology Company"],
    "EPI": ["Other"],
    "Finastra": ["Technology Company"],
    "Fusion Bank": ["Issuing Bank" "Acquiring Bank"],
    "Guaranty Trust": ["Issuing Bank" "Acquiring Bank"],
    "KREDA": ["Issuing Bank" "Acquiring Bank"],
    "Neem": ["Payment Processor" "Payment Gateway"],
    "Neonomics": ["Payment Processor" "Payment Gateway"],
    "PhonePe": ["Payment Processor" "Payment Gateway"],
    "QIB": ["Issuing Bank" "Acquiring Bank"],
    "Sohar": ["Issuing Bank" "Acquiring Bank"],
    "Standard Life": ["Issuing Bank" "Acquiring Bank"],
    "Travelex": ["Other"],
    "Veem": ["Payment Processor" "Payment Gateway"],
    "Veridas": ["Technology Company"],
    "Bluefin": ["Technology Company"],
    "Equifax": ["Technology Company"],
    "Fujitsu": ["Technology Company"],
    "NICE Actimize": ["Technology Company"],
    "Shufti Pro": ["Technology Company"],
    "SumUp": ["Payment Processor" "Payment Gateway"],
    "Thales": ["Technology Company"],
    "Truist": ["Issuing Bank" "Acquiring Bank"],
    "Varo Bank": ["Issuing Bank" "Acquiring Bank"],
    "VendorInfo": ["Other"],
    "Vero": ["Technology Company"],
    "CGI": ["Technology Company"],
    "Chipper Cash": ["Payment Processor" "Payment Gateway"],
    "CoinEx": ["Other"],
    "Develo": ["Issuing Bank" "Acquiring Bank"],
    "eToro": ["Technology Company"],
    "FreedomPay": ["Payment Processor" "Payment Gateway"],
    "Legit Security": ["Technology Company"],
    "Mondu": ["Other"],
    "Salmon": ["Other"],
    "Sandbox Banking": ["Other"],
    "Sumsub": ["Technology Company"],
    "Sybrin": ["Technology Company"],
    "U.S. Bank": ["Issuing Bank" "Acquiring Bank"],
    "360tf": ["Other"],
    "ACI Worldwide": ["Payment Processor" "Technology Company"],
    "Akoya": ["Technology Company"],
    "BNY Mellon": ["Issuing Bank" "Acquiring Bank"],
    "Brex": ["Other"],
    "Currencies Direct": ["Payment Processor" "Foreign Exchange"],
    "Flex": ["Other"],
    "Froda": ["Other"],
    "HSBC": ["Issuer" "Acquirer" "Payment Processor"],
    "IDEX Biometrics": ["Technology Company"],
    "InfinitePay": ["Other"],
    "Ingenico": ["Payment Processor" "Payment Gateway" "Acquirer"],
    "iProov": ["Technology Company"],
    "Know Your Customer": ["Technology Company"],
    "Novo": ["Issuing Bank" "Acquiring Bank"],
    "Oracle": ["Technology Company"],
    "PAX": ["Other"],
    "Payoneer": ["Payment Processor" "Payment Gateway"],
    "SAP Fioneer": ["Other"],
    "Tipalti": ["Payment Processor" "Payment Gateway"],
    "Ant Group": ["Technology Company"],
    "Bank of America": ["Issuing Bank" "Acquiring Bank"],
    "Fabrick": ["Technology Company"],
    "FinMont": ["Other"],
    "HAYVN": ["Other"],
    "Intesa Sanpaolo": ["Issuing Bank" "Acquiring Bank"],
    "Libra Internet Bank": ["Issuing Bank" "Acquiring Bank"],
    "Payflow": ["Payment Processor" "Payment Gateway"],
    "Saxo Bank": ["Other"],
    "SentiLink": ["Technology Company"],
    "Trade Ledger": ["Technology Company"],
    "Waave": ["Other"],
    "Apiture": ["Technology Company"],
    "Balance": ["Other"],
    "Banque Delubac": ["Issuing Bank" "Acquiring Bank"],
    "Basikon": ["Other"],
    "Blackbullion": ["Other"],
    "Broadridge": ["Technology Company"],
    "Credolab": ["Technology Company"],
    "EBANX": ["Payment Processor" "Payment Gateway"],
    "EMVCo": ["Technology Company"],
    "Hapana": ["Other"],
    "IBM": ["Technology Company"],
    "Judo Bank": ["Issuing Bank" "Acquiring Bank"],
    "Sendwave": ["Other"],
    "SWIFT": ["Payment Processor" "Payment Gateway"],
    "Tamatem Plus": ["Technology Company"],
    "Treasury Prime": ["Technology Company"],
    "UnionPay International": ["Payment Processor" "Payment Gateway"],
    "Bitwave": ["Other"],
    "BlueSnap": ["Payment Gateway" "Payment Processor"],
    "CRED": ["Other"],
    "EBA CLEARING": ["Technology Company"],
    "Fipto": ["Other"],
    "GEP": ["Technology Company"],
    "Gr4vy": ["Other"],
    "IDVerse": ["Technology Company"],
    "IndusInd Bank": ["Issuing Bank" "Acquiring Bank"],
    "LuLu Money": ["Other"],
    "Manigo": ["Technology Company"],
    "MoneyCollect": ["Other"],
    "NEC": ["Technology Company"],
    "Oobit": ["Payment Processor" "Payment Gateway"],
    "Paysend": ["PISP" "Payment Processor" "Payment Gateway"],
    "Playtech": ["Technology Company"],
    "Prelim": ["Other"],
    "Recharge": ["Other"],
    "Zoho": ["Technology Company"],
    "AFSOL": ["Other"],
    "Alpha Group": ["Other"],
    "Bankjoy": ["Technology Company"],
    "Capgemini": ["Technology Company"],
    "Episode Six": ["Technology Company"],
    "Hokodo": ["Technology Company"],
    "Intuit": ["Technology Company"],
    "JT Group": ["Other"],
    "Nethone": ["Technology Company"],
    "Nubank": ["Issuing Bank" "Acquiring Bank"],
    "Open Banking": ["Other"],
    "Opera": ["Technology Company"],
    "PwC": ["Other"],
    "SBI": ["Issuing Bank" "Acquiring Bank"],
    "Telegram": ["Technology Company"],
    "YouAttest": ["Other"],
    "BitPay": ["Payment Processor" "eWallet"],
    "Caliza": ["Other"],
    "Corpay": ["Other"],
    "CSG Forte": ["Technology Company"],
    "Deduce": ["Other"],
    "Deloitte": ["Payment Processor" "Payment Gateway"],
    "EBL": ["Issuing Bank" "Acquiring Bank"],
    "Foro": ["Other"],
    "Fountain": ["Other"],
    "Marygold": ["Technology Company"],
    "Mibanco": ["Issuing Bank" "Acquiring Bank"],
    "Owlin": ["Technology Company"],
    "Perfios": ["Technology Company"],
    "RAKBANK": ["Issuing Bank" "Acquiring Bank"],
    "Scotiabank": ["Issuing Bank" "Acquiring Bank"],
    "VANKLIA": ["Other"],
    "BIAN": ["Technology Company"],
    "Sprinque": ["Other"],
    "Treyd": ["Other"],
    "TikTok": ["Technology Company"],
    "Wintranx": ["Other"],
    "Wix": ["Technology Company"],
    "Alibaba": ["Technology Company"],
    "Archie": ["Technology Company"],
    "AUB": ["Issuing Bank" "Acquiring Bank"],
    "Finance": ["Other"],
    "Firework": ["Technology Company"],
    "Flutterwave": ["Payment Processor" "Payment Gateway"],
    "Fonepay": ["Payment Processor" "Payment Gateway"],
    "Solid": ["Other"],
    "Affirm": ["Technology Company"],
    "Certa": ["Other"],
    "Hyundai": ["Other"],
    "Instacart": ["Technology Company"],
    "JP Morgan": ["Acquirer" "Issuer" "Payment Processor"],
    "Momnt": ["Other"],
    "Nagad": ["Payment Processor" "Payment Gateway"],
    "PayU": ["Payment Gateway" "Payment Processor"],
    "Upvest": ["Other"],
    "Zopa": ["Payment Processor" "Payment Gateway"],
    "APEXX": ["Other"],
    "Arendt": ["Other"],
    "Central Payments": ["Payment Processor" "Payment Gateway"],
    "Esker": ["Technology Company"],
    "Idemia": ["Technology Company"],
    "JCB": ["Card Scheme"],
    "Ledger": ["Technology Company"],
    "LHV Bank": ["Issuing Bank" "Acquiring Bank"],
    "NPCI": ["Technology Company"],
    "Paysafe": ["Payment Gateway" "Payment Processor"],
    "Strise": ["Payment Processor" "Payment Gateway"],
    "3S Money": ["Payment Processor" "Payment Gateway"],
    "Bank of Canada": ["Other"],
    "Blackhawk Network": ["Payment Processor" "Payment Gateway"],
    "Bluevine": ["Payment Processor" "Payment Gateway"],
    "Credit Sesame": ["Other"],
    "Crunchfish": ["Technology Company"],
    "Factris": ["Other"],
    "FundingShield": ["Other"],
    "GXBank": ["Other"],
    "IDnow": ["Technology Company"],
    "Kotani": ["Technology Company"],
    "Ntropy": ["Technology Company"],
    "PayRetailers": ["Payment Processor" "Payment Gateway"],
    "PayU India": ["Payment Processor" "Payment Gateway"],
    "SAB": ["Other"],
    "Tell.money": ["Other"],
    "Anchor": ["Payment Processor" "Payment Gateway"],
    "Coinstash": ["Other"],
    "Complii": ["Other"],
    "CPBank": ["Issuing Bank" "Acquiring Bank"],
    "FutureBank": ["Issuing Bank" "Acquiring Bank"],
    "GenTwo": ["Technology Company"],
    "Huawei": ["Technology Company"],
    "Incard": ["Payment Processor" "Payment Gateway"],
    "J.P. Morgan": ["Issuing Bank" "Acquiring Bank"],
    "Paybis": ["Payment Processor" "Payment Gateway"],
    "Pliant": ["Other"],
    "Qover": ["Other"],
    "SAMA": ["Issuing Bank" "Acquiring Bank"],
    "Signicat": ["Technology Company"],
    "ThetaRay": ["Technology Company"],
    "Wamo": ["Technology Company"],
    "ACE Money": ["Other"],
    "Acquired.com": ["Other"],
    "Arab Financial": ["Issuing Bank" "Acquiring Bank"],
    "Astra Tech": ["Other"],
    "Banking Circle": ["Other"],
    "Bybit": ["Other"],
    "Cashfree Payments": ["Payment Processor" "Payment Gateway"],
    "Clear Junction": ["Other"],
    "CyberConnect": ["Technology Company"],
    "FedTech": ["Technology Company"],
    "Gate.io": ["Other"],
    "OneCard": ["Issuing Bank" "Acquiring Bank"],
    "Infosys": ["Technology Company"],
    "LSE Group": ["Other"],
    "MIDBANK": ["Other"],
    "Morabaha Marina": ["Other"],
    "Paytm": ["PISP" "Payment Processor" "Payment Gateway"],
    "Pine Labs": ["Payment Processor" "Payment Gateway"],
    "Safexpay": ["Payment Processor" "Payment Gateway"],
    "Yes Bank": ["Issuer" "Acquiring Bank"],
    "Alkami": ["Technology Company"],
    "Atlantic": ["Other"],
    "BingX": ["Other"],
    "BlinkPay": ["Payment Processor" "Payment Gateway"],
    "Circle": ["Payment Processor" "Payment Gateway"],
    "Coda": ["Other"],
    "Conferma Pay": ["Payment Processor" "Payment Gateway"],
    "Expensify": ["Technology Company"],
    "LAB Group": ["Technology Company"],
    "Nexo": ["Other"],
    "Rho": ["Other"],
    "Tether": ["Payment Processor" "Payment Gateway"],
    "TrueNorth": ["Other"],
    "Vic.ai": ["Other"],
    "World Bank": ["Other"],
    "ZeroPay": ["Payment Processor" "Payment Gateway"],
    "aiBANK": ["Other"],
    "Arkose Labs": ["Technology Company"],
    "Bloomreach": ["Technology Company"],
    "Google": ["BigTech"],
    "Hallmark": ["Technology Company"],
    "Ivy": ["Technology Company"],
    "OnBuy": ["Other"],
    "Pelican AI": ["Technology Company"],
    "SEPAY": ["Other"],
    "TymeBank": ["Issuing Bank" "Acquiring Bank"],
    "Elavon": ["Acquirer" "Issuer" "Payment Processor"],
    "Uplinq": ["Other"],
    "X": ["Technology Company"],
    "Zil Money": ["Other"],
    "AmTrust": ["Technology Company"],
    "Astra": ["Other"],
    "Aumentum": ["Other"],
    "BofA": ["Issuing Bank" "Acquiring Bank"],
    "CommentSold": ["Technology Company"],
    "Dash": ["Technology Company"],
    "Diebold Nixdorf": ["Technology Company"],
    "docStribute": ["Technology Company"],
    "GoCardless": ["Payment Processor" "Direct Debit Services"],
    "Injective": ["Technology Company"],
    "Ivalua": ["Technology Company"],
    "Orbyt": ["Technology Company"],
    "Qarar": ["Technology Company"],
    "SEBA Bank": ["Issuing Bank" "Acquiring Bank"],
    "VizyPay": ["Payment Processor" "Technology Company"],
    "Afreximbank": ["Issuing Bank" "Acquiring Bank"],
    "Argus": ["Technology Company"],
    "BBVA": ["Issuing Bank" "Acquiring Bank"],
    "BMO": ["Issuing Bank" "Acquiring Bank"],
    "FOMO": ["Other"],
    "GO Markets": ["Other"],
    "Mercuryo": ["Payment Processor" "Payment Gateway"],
    "Orion Innovation": ["Technology Company"],
    "PandaDoc": ["Technology Company"],
    "PAPSS": ["Technology Company"],
    "PayU GPO": ["Other"],
    "Tabby": ["Payment Processor" "Payment Gateway"],
    "Trustly": ["Payment Processor" "PISP"],
    "Ukheshe": ["Payment Processor" "Payment Gateway"],
    "VSoft": ["Technology Company"],
    "WALBING": ["Other"],
    "Yahoo": ["Technology Company"],
    "BEST Vietnam": ["Issuing Bank" "Acquiring Bank"],
    "Bitfinex": ["Other"],
    "FICO": ["Technology Company"],
    "FIDO Alliance": ["Digital ID"],
    "FinBox": ["Technology Company"],
    "GHL": ["Technology Company"],
    "GLN": ["Other"],
    "Griffin": ["Technology Company"],
    "Instacart files": ["Technology Company"],
    "LemFi": ["Other"],
    "Mangold Fondkommission": ["Other"],
    "Membrane": ["Technology Company"],
    "M-Pesa": ["Payment Processor" "Payment Gateway"],
    "Safaricom": ["Technology Company"],
    "Sharjah Entrepreneurship": ["Technology Company"],
    "State Bank": ["Issuing Bank" "Acquiring Bank"],
    "Trulioo augments": ["Technology Company"],
    "USAA becomes": ["Technology Company"],
    "Zepto": ["Technology Company"],
    "Alpha Bank": ["Issuing Bank" "Acquiring Bank"],
    "B2C": ["Other"],
    "Citi makes": ["Issuing Bank" "Acquiring Bank"],
    "ClearSale": ["Technology Company"],
    "FSS": ["Technology Company"],
    "KEPF": ["Other"],
    "Marqeta": ["Payment Processor" "Technology Company"],
    "N26": ["Issuing Bank" "Acquiring Bank"],
    "Nedbank": ["Issuing Bank" "Acquiring Bank"],
    "Shopmium": ["Technology Company"],
    "Standard AI": ["Technology Company"],
    "The UAE": ["Other"],
    "TSG": ["Other"],
    "Bamboo Payment": ["Payment Processor" "Payment Gateway"],
    "ComplyAdvantage": ["Technology Company"],
    "DataArt": ["Technology Company"],
    "EIF": ["Technology Company"],
    "Finqware": ["Technology Company"],
    "Guavapay": ["Payment Processor" "Payment Gateway"],
    "Krakowski Bank": ["Issuing Bank" "Acquiring Bank"],
    "Macau Pass": ["Payment Processor" "Payment Gateway"],
    "Mast General": ["Other"],
    "Moneysoft": ["Technology Company"],
    "PatientPay": ["Technology Company"],
    "Quantstamp": ["Technology Company"],
    "ResearchAndMarkets": ["Technology Company"],
    "Solana Pay": ["Payment Processor" "Payment Gateway"],
    "SpyCloud": ["Technology Company"],
    "Supercharge": ["Other"],
    "TreasurUp": ["Technology Company"],
    "Zorrz": ["Other"],
    "Beyond": ["Other"],
    "Checkout.com": ["Payment Gateway" "Payment Processor"],
    "Five Star": ["Technology Company"],
    "FNBO": ["Issuing Bank" "Acquiring Bank"],
    "IFX Payments": ["Technology Company"],
    "Koverly": ["Other"],
    "Moniepoint": ["Issuing Bank" "Acquiring Bank"],
    "Nium": ["Payment Processor" "Payment Gateway"],
    "Nomad": ["Technology Company"],
    "OANDA": ["Technology Company"],
    "Ramp": ["Payment Processor" "Payment Gateway"],
    "Reserve Bank": ["Technology Company"],
    "OpenWallet": ["Other"],
    "True Digital": ["Other"],
    "Yeeld": ["Other"],
    "Altum Group": ["Technology Company"],
    "ASAL Microfinance": ["Issuing Bank" "Acquiring Bank"],
    "Chinabank": ["Issuing Bank" "Acquiring Bank"],
    "Clara": ["Technology Company"],
    "Colendi gets": ["Technology Company"],
    "Cynergy Bank": ["Issuing Bank" "Acquiring Bank"],
    "DMALINK collaborates": ["Technology Company"],
    "Dock": ["Technology Company"],
    "EchoPay": ["Payment Processor" "Payment Gateway"],
    "Eltropy": ["Technology Company"],
    "Paradigm Sports": ["Technology Company"],
    "Tamilnad Mercantile": ["Issuing Bank" "Acquiring Bank"],
    "Tap-to": ["Other"],
    "Tbi Bank": ["Issuing Bank" "Acquiring Bank"],
    "Teamwork Commerce": ["Technology Company"],
    "Thales empowers": ["Technology Company"],
    "TreviPay": ["Payment Processor" "Payment Gateway"],
    "Vista": ["Technology Company"],
    "VU": ["Other"],
    "Atome Financial": ["Payment Processor" "Payment Gateway"],
    "Cambodia": ["Other"],
    "DBS Bank": ["Issuing Bank" "Acquiring Bank"],
    "MOIN": ["Payment Processor" "Payment Gateway"],
    "New UK": ["Other"],
    "OMNIA": ["Other"],
    "Reltime": ["Other"],
    "Newstore": ["Technology Company"],
    "Alpaca": ["Technology Company"],
    "Hifi": ["Technology Company"],
    "Credova": ["Payment Processor" "Payment Gateway"],
    "Numis": ["Technology Company"],
    "Paydora Finance": ["Payment Processor" "Payment Gateway"],
    "Plaid": ["Technology Company"],
    "Triple-A": ["Other"],
    "Xero": ["Technology Company"],
    "Lazada": ["Other"],
    "Currencycloud": ["Technology Company"],
    "Ordo": ["Payment Processor" "Payment Gateway"],
    "US Discover": ["Technology Company"],
    "Satispay": ["Payment Processor" "Payment Gateway"],
    "Snowdrop Solutions": ["Technology Company"],
    "Skytef": ["Payment Processor" "Payment Gateway"],
    "Lumin Digital": ["Technology Company"],
    "nCino": ["Technology Company"],
    "Bizom": ["Technology Company"],
    "P12": ["Other"],
    "Fibe": ["Other"],
    "Versana": ["Technology Company"],
    "Global Anti-Scam Alliance": ["Other"],
    "Unlimit": ["Technology Company"],
    "finbotsAI": ["Technology Company"],
    "Paze": ["Other"],
    "GreenSky": ["Other"],
    "Payment Visor": ["Payment Processor" "Payment Gateway"],
    "Fortress Trust": ["Other"],
    "Mambu": ["Technology Company"],
    "HKEX Synapse": ["Other"],
    "GCash": ["Other"],
    "Securities Services": ["Other"],
    "Superbank": ["Other"],
    "BCM": ["Other"],
    "Worldpay": ["Payment Processor" "Payment Gateway"],
    "Microsoft": ["BigTech"],
    "NSDL": ["Other"],
    "ONESOURCE": ["Other"],
    "TripLink": ["Other"],
    "Bancolombia": ["Issuing Bank" "Acquiring Bank"],
    "NomadRem": ["Other"],
    "NextWealth": ["Other"],
    "Peacock": ["Other"],
    "AMLYZE": ["Other"],
    "eCU": ["Other"],
    "FLOOSS": ["Other"],
    "ibanXS": ["Other"],
    "KuCoin": ["Other"],
    "Motive Partners": ["Other"],
    "Programme": ["Other"],
    "Bank": ["Issuing Bank" "Acquiring Bank"],
    "Pay": ["Payment Processor" "Payment Gateway"],
    "Qlik": ["Technology Company"],
    "ECPay": ["Payment Processor" "Payment Gateway"],
    "Lucca": ["Other"],
    "Veefin Solution": ["Other"],
    "Keebo": ["Other"],
    "UBank": ["Issuing Bank" "Acquiring Bank"],
    "Integrity": ["Other"],
    "Marketplace": ["Other"],
    "Shopify": ["Technology Company"],
    "Trovata": ["Technology Company"],
    "Aircash": ["Other"],
    "Paywatch": ["Other"],
    "TX Ventures": ["Other"],
    "Green Dot": ["Issuer" "Payment Processor" "Acquirer"],
    "Cable": ["Other"],
    "NextGen": ["Technology Company"],
    "paymints.io": ["Payment Processor" "Payment Gateway"],
    "Tickets Travel Network": ["Other"],
    "Paymentwall": ["Payment Processor" "Payment Gateway"],
    "SoftBank": ["Technology Company"],
    "SpotOn": ["Technology Company"],
    "Pidgin": ["Other"],
    "BlackRock": ["Other"],
    "Tesselate": ["Other"],
    "SeaPay": ["Payment Processor" "Payment Gateway"],
    "Fourthline": ["Technology Company"],
    "Access Africa": ["Other"],
    "Expel": ["Technology Company"],
    "Comma": ["Other"],
    "Aliaswire": ["Other"],
    "L&C": ["Other"],
    "Sage": ["Payment Processor" "Payment Gateway"],
    "Zero Hash": ["Technology Company"],
    "Kamma": ["Other"],
    "BlockFold": ["Other"],
    "Thought Machine": ["Technology Company"],
    "Havas": ["Other"],
    "Alipay": ["PISP" "Payment Processor" "Payment Gateway"],
    "Codebase": ["Technology Company"],
    "Aconomy": ["Other"],
    "nTokens": ["Other"],
    "Onfido": ["Digital ID"],
    "dLocal": ["Payment Processor" "Payment Gateway"],
    "Jack Henry": ["Other"],
    "Clip Money": ["Payment Processor" "Payment Gateway"],
    "Checkmarx": ["Technology Company"],
    "QRails": ["Payment Processor" "Payment Gateway"],
    "Plend": ["Other"],
    "CommEX": ["Other"],
    "Cash App Pay": ["Payment Processor" "Payment Gateway"],
    "Afterpay": ["Payment Processor" "Payment Gateway"],
    "Netcetera": ["Technology Company"],
    "Datacap": ["Technology Company"],
    "ABHI": ["Other"],
    "YellowPepper": ["Other"],
    "Konsentus": ["Technology Company"],
    "Zimpler": ["Payment Processor" "Payment Gateway"],
    "Droit": ["Technology Company"],
    "in3": ["Other"],
    "VTEX": ["Other"],
    "Tuily": ["Other"],
    "Consensys": ["Technology Company"],
    "AvecPay": ["Payment Processor" "Payment Gateway"],
    "Give Lively": ["Other"],
    "Starfish": ["Other"],
    "Standard Bank": ["Issuing Bank" "Acquiring Bank"],
    "Onramper": ["Other"],
    "Fasset": ["Other"],
    "Synapsify": ["Technology Company"],
    "Anthropic": ["Technology Company"],
    "BrankieOne": ["Other"],
    "Corvallis": ["Other"],
    "WeBank": ["Issuing Bank" "Acquiring Bank"],
    "BetterNow": ["Other"],
    "Mascap": ["Other"],
    "Moneyhub": ["Technology Company"],
    "Mitek": ["Technology Company"],
    "Asset Reality": ["Other"],
    "GoTyme": ["Other"],
    "Newton Global": ["Other"],
    "Intel": ["Technology Company"],
    "Infineon": ["Technology Company"],
    "CRV": ["Other"],
    "Regula": ["Technology Company"],
    "Ebury": ["Payment Processor" "Payment Gateway"],
    "Envestnet": ["Technology Company"],
    "Yodlee": ["Technology Company"],
    "Transact": ["Other"],
    "KL HI-TECH": ["Technology Company"],
    "Diggercard": ["Other"],
    "Ping": ["Other"],
    "Airbnb": ["Other"],
    "dtcpay": ["Payment Processor" "Payment Gateway"],
    "MIND DXM": ["Technology Company"],
    "Hilbert": ["Other"],
    "MiCA": ["Other"],
    "Saxo": ["Other"],
    "Greenlight": ["Other"],
    "Numeral": ["Other"],
    "Circulo de Credito": ["Other"],
    "Nova Credit": ["Other"],
    "Gilded": ["Other"],
    "BigTime": ["Technology Company"],
    "Datos Insights": ["Technology Company"],
    "Taurus": ["Other"],
    "Kestrl": ["Other"],
    "Nimo": ["Other"],
    "Endava": ["Technology Company"],
    "SurePay": ["Payment Processor" "Payment Gateway"],
    "Colony": ["Other"],
    "Startselect": ["Other"],
    "RedWeek": ["Other"],
    "Public": ["Other"],
    "Fime": ["Technology Company"],
    "Cobase": ["Other"],
    "Panacea": ["Other"],
    "Honey Badger": ["Other"],
    "Verifi": ["Payment Processor" "Technology Company"],
    "BVNK": ["Other"],
    "Celo": ["Other"],
    "Clearspeed": ["Technology Company"],
    "Petit Bateau": ["Other"],
    "Auctionet": ["Other"],
    "ekko": ["Other"],
    "Bridge": ["Other"],
    "Branch": ["Other"],
    "Cybernetica": ["Technology Company"],
    "Incode": ["Technology Company"],
    "Sardine": ["Other"],
    "BankAxept": ["Other"],
    "Form3": ["Technology Company"],
    "Rongbao": ["Other"],
    "NIPL": ["Technology Company"],
    "Inpay": ["Payment Processor" "Payment Gateway"],
    "Trust": ["Other"],
    "Lewis & Clark": ["Other"],
    "Booking": ["Technology Company"],
    "Bankify": ["Technology Company"],
    "Salesforce": ["Technology Company"],
    "KredX": ["Technology Company"],
    "Meta": ["BigTech"],
    "AML": ["Compliance" "Technology Company"],
    "Fenergo": ["Compliance" "Technology Company"],
    "Waddle": ["Technology Company"],
    "Boost": ["Other"],
    "Bridgewise": ["Technology Company"],
    "Airtel": ["Other"],
    "PAYONE": ["Payment Processor" "Payment Gateway"],
    "Kriya": ["Other"],
    "Eightcap": ["Other"],
    "LISNR": ["Technology Company"],
    "Tata": ["Other"],
    "Icon": ["Technology Company"],
    "Yapily": ["Technology Company"],
    "HyperPay": ["Payment Processor" "Payment Gateway"],
    "CommercePro": ["Technology Company"],
    "Cloud Finance": ["Technology Company"],
    "Colossos": ["Technology Company"],
    "DECTA": ["Payment Processor" "Payment Gateway"],
    "Solana": ["Technology Company"],
    "Investified": ["Technology Company"],
    "MIntegrity": ["Technology Company"],
    "Eurogiro": ["Payment Processor" "Payment Gateway"],
    "Friday": ["Technology Company"],
    "Moldur": ["Technology Company"],
    "Polygon CDK": ["Technology Company"],
    "Alfalah": ["Issuing Bank" "Acquiring Bank"],
    "Jamboree": ["Other"],
    "Altalix": ["Other"],
    "Komgo": ["Technology Company"],
    "Tookitaki": ["Technology Company"],
    "Mercado Pago": ["Payment Processor" "Payment Gateway"],
    "Mobily": ["Other"],
    "Inlogik": ["Technology Company"],
    "functionality": ["Other"],
    "Truecaller": ["Technology Company"],
    "Capital": ["Technology Company"],
    "PayMate": ["Technology Company"],
    "Britannia": ["Technology Company"],
    "RADD": ["Other"],
    "IDB": ["Issuing Bank" "Acquiring Bank"],
    "Nu": ["Technology Company"],
    "Venmo": ["PISP" "Payment Processor" "Payment Gateway"],
    "Everset": ["Other"],
    "Surecomp": ["Technology Company"],
    "Buckaroo": ["Payment Processor" "Payment Gateway"],
    "PayShap": ["Payment Processor" "Payment Gateway"],
    "Kiwibank": ["Issuing Bank" "Acquiring Bank"],
    "PremiumPay": ["Payment Processor" "Payment Gateway"],
    "Shredder": ["Technology Company"],
    "KyckGlobal": ["Payment Processor" "Payment Gateway"],
    "Pegasystems": ["Technology Company"],
    "Commusoft": ["Technology Company"],
    "C6": ["Technology Company"],
    "Tink": ["Technology Company"],
    "Moneythor": ["Technology Company"],
    "Biz2X": ["Technology Company"],
    "Clear Lake": ["Technology Company"],
    "StarCompliance": ["Compliance" "Technology Company"],
    "Notabene": ["Compliance" "Technology Company"],
    "Denario": ["Technology Company"],
    "Diamond Trust": ["Issuing Bank" "Acquiring Bank"],
    "Techcombank": ["Issuing Bank" "Acquiring Bank"],
    "Vakıfbank": ["Issuing Bank" "Acquiring Bank"],
    "IIFL": ["Technology Company"],
    "Crosskey": ["Technology Company"],
    "Ingiz": ["Technology Company"],
    "NymCard": ["Payment Processor" "Payment Gateway"],
    "Orange Money": ["Payment Processor" "Payment Gateway"],
    "Rextie": ["Payment Processor" "Payment Gateway"],
    "Giftbit": ["Technology Company"],
    "Sergel": ["Technology Company"],
    "SavvyMoney": ["Technology Company"],
    "inDrive": ["Technology Company"],
    "Avalara": ["Technology Company"],
    "Sileon": ["Technology Company"],
    "Kopo": ["Technology Company"],
    "OZ": ["Technology Company"],
    "Ncontracts": ["Technology Company"],
    "Feedzai": ["Technology Company"],
    "ZooPay": ["Payment Processor" "Payment Gateway"],
    "TransferMate": ["Payment Processor" "Payment Gateway"],
    "Jocata": ["Technology Company"],
    "NovoPayment": ["Technology Company"],
    "Checkout": ["Technology Company"],
    "Qashio": ["Technology Company"],
    "Drex": ["Technology Company"],
    "GNB": ["Issuing Bank" "Acquiring Bank"]
    }


